import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import AddGameCardForm from "../components/Form/GameCardForm";
import GameCard from "../components/GameCard/GameCard";
import Form from "./form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledMain>
        <h1>My App</h1>
        <Link href="/gameplan" passHref>
          <Anchor>gameplan</Anchor>
        </Link>
        <Link href="/form" passHref>
          <Anchor>form</Anchor>
        </Link>
      </StyledMain>
    </div>
  );
}

const StyledMain = styled.main`
  text-align: center;
`;

const Anchor = styled.a`
  margin: 2em;
`;
