import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import AnchorLink from "../components/StyledLink";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainWrapper>
        <h1>My App</h1>
        <Image
          src="/assets/Entry_Image_2400x1600.jpg"
          alt="Entry image"
          layout="fill"
          objectFit="cover"
          width={2400}
          height={1600}
        />
        <Link href="/gamelist" passHref>
          <StyledHeadline>Click to enter...</StyledHeadline>
        </Link>
      </MainWrapper>
    </div>
  );
}

const MainWrapper = styled.main`
  text-align: center;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 2em;
  height: 100vh;
`;

const StyledHeadline = styled.h1`
  position: absolute;
  bottom: 25%;
  z-index: 200;
  color: #fff;

  :hover {
    color: var(--attention-color-primary);
    cursor: pointer;
  }
`;
